version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: